### PR TITLE
Pose estimator merge

### PR DESCRIPTION
**Pull request by AidanDonnelly1**
Note that the tuning of standard deviations still needs to be done.

Things to double check:
- proper merge, could have merged the drivetrain constructor wrong
- proper use of robot geometry, particular operating in the proper quadrant

### CODE REVIEW

**Comment by gcschmit** [comment]
@AidanDonnelly1 Would you share a link to the documentation you referenced when coding this? That context would be helpful.

Also, is the plan to use the pose for aiming instead of using the Limelight and gyro directly? If so, should that be part of this pull request as well?

**Comment by AidanDonnelly1** [comment]
> @AidanDonnelly1 Would you share a link to the documentation you referenced when coding this? That context would be helpful.
> 
> Also, is the plan to use the pose for aiming instead of using the Limelight and gyro directly? If so, should that be part of this pull request as well?

I just made a trello card that has all the documentation I used: https://trello.com/c/k11me8LT/349-pose-estimation

I initially did most of this over the summer, so my intent in finishing it now was just to not leave an unfinished project. That being said I didn't have a specific plan for how we would use this. I think a could start would be using it anywhere we currently use Pose and use pose estimator(i.e. logging, shuffle board), and then similar to orbit that graphical representation that highlights where skids happens would be pretty cool. I didn't have any specific plans for using the pose estimator to aim, but if you think this would be a could idea I can do so.

**Comment by cyandev** [comment]
I'm not sure if the final pose we are returning is correct (I think I made a mistake in my original document). Right now, the final pose outputted is:

```java
return new Pose2d(
        hubLocation.plus(cameraToVisionTarget.inverse().getTranslation()),
        new Rotation2d(this.inputs.yaw));
```

What this does is it takes the (unrotated) translation from field (0,0) to the hub and adds the (unrotated) camera-to-vision-target translation. This fails to take into account the robot's rotation as we are only adding translations. I'm pretty sure the way to fix this would be something like this:
```java
return new Pose2d(hubLocation, this.inputs.yaw).minus(cameraToVisionTarget);
```
This approach takes the hubLocation and applies the robot's rotation to it, creating a pose as if the robot was translated into the vision target. Then it applies the cameraToVisionTarget translation backwards, translating the robot to it's correct position. This is similar to the way 6328 did it (but more elegant imo):
```java
Transform2d fieldToTargetRotated =
    new Transform2d(FieldConstants.hubCenter, cameraRotation);
Transform2d fieldToCamera = fieldToTargetRotated.plus(GeomUtil
    .transformFromTranslation(cameraToTargetTranslation.unaryMinus()));
Pose2d fieldToVehicle = GeomUtil.transformToPose(
    fieldToCamera.plus(cameraPosition.vehicleToCamera.inverse()));
```

**Comment by cyandev** [comment]
@gcschmit The reason we need the rotation before the last step is that without it we aren't in a robot-relative rotation, which is crucial before applying the inverse of the robotToVisionTarget transform. I attached a diagram that tries to explain why it's important.
Diagram

I'm not sure why the minus method doesn't accept a transformation, we should just add the inverse instead.
`return new Pose2d(hubLocation, this.inputs.yaw).plus(cameraToVisionTarget.inverse());`

**Comment by gcschmit** [comment]
@cyandev Okay, I totally missed that. Your explanation makes sense; thanks for the drawings. I did the matrix math by hand for an example to make sure I was understanding. I guess the key is that a Transform2D is a relative transformation (i.e., from the robot's perspective) and therefore the initial pose needs to reflect the robot's rotation. Just to ensure I'm following, the cameraToVisionTarget transformation has no rotational component because, from the robot's perspective, it's just a translation. Is that correct?

I pushed a change that matches your latest suggestion.

**Comment by gcschmit** [comment]
@cyandev Did you update your document to reflect this new understanding?

**Comment by gcschmit** [comment]
Read on Chief Delphi: "SwerveDrivePoseEstimator is getting an [update](https://github.com/wpilibsuite/allwpilib/pull/4493/commits) to allow the use use Wheel Positions instead of the velocity estimates in SwerveModuleState. There is a new class called SwerveModulePosition."

When we pull in these changes, we should create an issue to upgrade the code to use the new feature in next year's code.

**Pull request merged**
